/*******************************************************************************
   Include file Furuta_Model_dsmpbap.c:

   Declaration of asynchronous tasks generated by DSMPB Trigger Event Block

   Wed Aug 14 16:13:35 2024

   (c) Copyright 2020, dSPACE GmbH. All rights reserved.

 ******************************************************************************/

#include "Furuta_Model_dsmpbap.h"
#include "Furuta_Model.h"
#include "Furuta_Model_private.h"

/* Declarations of trigger task access points            */
/* Access point for triggered task function of block Furuta_Model/Hardware-Triggered Runnable Function2/Trigger Event Port S-Fcn    */
void dsmpb_event_task_Furuta_Model_TriggerEventPortSFcn_b_TID0_BT1(void)
{
}

/* Access point for triggered task function of block Furuta_Model/Software-Triggered Runnable Function/Trigger Event Port S-Fcn    */
void dsmpb_event_task_Furuta_Model_TriggerEventPortSFcn_TID3_BT2(void)
{
  /* Local variables for absolute time support */
  real_T absTime = 0;

  /* Update counters for absolute time support */
  DSMPB_AbsoluteTimeGet(&absTime);
  Furuta_Model_M->Timing.clockTickH3 = (uint32_T)(absTime);
  Furuta_Model_M->Timing.clockTick3 = (uint32_T)((absTime-(uint32_T)(absTime))*
    4294967296.0);
  Furuta_Model_M->Timing.t[3] = Furuta_Model_M->Timing.clockTick3 *
    Furuta_Model_M->Timing.stepSize3 + Furuta_Model_M->Timing.clockTickH3 *
    Furuta_Model_M->Timing.stepSize3 * 4294967296.0;

  {
    int32_T i;

    /* RateTransition: '<Root>/Rate Transition5' */
    Furuta_Model_DW.RateTransition5_semaphoreTaken =
      Furuta_Model_DW.RateTransition5_ActiveBufIdx;
    Furuta_Model_B.RateTransition5 =
      Furuta_Model_DW.RateTransition5_Buffer[Furuta_Model_DW.RateTransition5_semaphoreTaken];

    /* RateTransition: '<Root>/Rate Transition6' */
    Furuta_Model_DW.RateTransition6_semaphoreTaken =
      Furuta_Model_DW.RateTransition6_ActiveBufIdx;
    Furuta_Model_B.RateTransition6 =
      Furuta_Model_DW.RateTransition6_Buffer[Furuta_Model_DW.RateTransition6_semaphoreTaken];

    /* RateTransition: '<Root>/Rate Transition7' */
    Furuta_Model_DW.RateTransition7_semaphoreTaken =
      Furuta_Model_DW.RateTransition7_ActiveBufIdx;
    Furuta_Model_B.RateTransition7 =
      Furuta_Model_DW.RateTransition7_Buffer[Furuta_Model_DW.RateTransition7_semaphoreTaken];

    /* RateTransition: '<Root>/Rate Transition8' */
    Furuta_Model_DW.RateTransition8_semaphoreTaken =
      Furuta_Model_DW.RateTransition8_ActiveBufIdx;
    Furuta_Model_B.RateTransition8 =
      Furuta_Model_DW.RateTransition8_Buffer[Furuta_Model_DW.RateTransition8_semaphoreTaken];

    /* S-Function (dsmpb_triggereventport): '<S12>/Trigger Event Port S-Fcn' */
    Furuta_Model_Acados();

    /* End of Outputs for S-Function (dsmpb_triggereventport): '<S12>/Trigger Event Port S-Fcn' */

    /* RateTransition: '<Root>/Counter' */
    Furuta_Model_DW.Counter_Buffer[Furuta_Model_DW.Counter_ActiveBufIdx == 0] =
      Furuta_Model_B.OutportBufferForCounter;
    Furuta_Model_DW.Counter_ActiveBufIdx = (int8_T)
      (Furuta_Model_DW.Counter_ActiveBufIdx == 0);

    /* RateTransition: '<Root>/I_ref Acados' */
    Furuta_Model_DW.I_refAcados_Buffer[Furuta_Model_DW.I_refAcados_ActiveBufIdx ==
      0] = Furuta_Model_B.Gain_h;
    Furuta_Model_DW.I_refAcados_ActiveBufIdx = (int8_T)
      (Furuta_Model_DW.I_refAcados_ActiveBufIdx == 0);

    /* RateTransition: '<Root>/Measure' */
    for (i = 0; i < 59; i++) {
      Furuta_Model_DW.Measure_Buffer[i + (Furuta_Model_DW.Measure_ActiveBufIdx ==
        0) * 59] = Furuta_Model_B.OutportBufferForMeasure[i];
    }

    Furuta_Model_DW.Measure_ActiveBufIdx = (int8_T)
      (Furuta_Model_DW.Measure_ActiveBufIdx == 0);

    /* End of RateTransition: '<Root>/Measure' */

    /* RateTransition: '<Root>/acados_on' */
    Furuta_Model_DW.acados_on_Buffer[Furuta_Model_DW.acados_on_ActiveBufIdx == 0]
      = Furuta_Model_B.OutportBufferForacados_on;
    Furuta_Model_DW.acados_on_ActiveBufIdx = (int8_T)
      (Furuta_Model_DW.acados_on_ActiveBufIdx == 0);
  }
}

/* Access point for triggered task function of block Furuta_Model/Hardware-Triggered Runnable Function1/Trigger Event Port S-Fcn    */
void dsmpb_event_task_Furuta_Model_TriggerEventPortSFcn_g_TID4_BT3(void)
{
  {
    /* S-Function (dsmpb_triggereventport): '<S9>/Trigger Event Port S-Fcn' */
    Furuta_Model_Subsystem();

    /* End of Outputs for S-Function (dsmpb_triggereventport): '<S9>/Trigger Event Port S-Fcn' */

    /* RateTransition: '<Root>/Acados_trigger_out' */
    Furuta_Model_DW.Acados_trigger_out_Buffer[Furuta_Model_DW.Acados_trigger_out_ActiveBufIdx
      == 0] = Furuta_Model_B.sf_MATLABFunction_b.y;
    Furuta_Model_DW.Acados_trigger_out_ActiveBufIdx = (int8_T)
      (Furuta_Model_DW.Acados_trigger_out_ActiveBufIdx == 0);
  }
}
